name: create a release and a tag it
on:
  push:
    branches:
      - master

jobs:
  simple:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Setup the release')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Set env // from https://stackoverflow.com/a/57969570
        run: |
          VERSION=$(
            LIBRARY_VERSION_MARKER="LIBRARY_VERSION" \
            awk -f .github/scripts/extract_library_version.awk gradle.properties
          )
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
          CHANGES=$(
            CHANGELOG_MARKER_START="### ${VERSION}" \
            CHANGELOG_MARKER_END="###" \
            awk -f .github/scripts/extract_release_notes.awk CHANGELOG.md
          )
          echo "CHANGES<<EOF" >> $GITHUB_ENV
          echo "$CHANGES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Print version
        run: echo "Version is $VERSION"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token

        with:
          tag_name: v${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          body: ${{ env.CHANGES }}
          draft: false
          prerelease: false
  package:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Setup the release')
    - steps:
      permissions:
        actions: write
      - name: Create package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run .github/workflows/gradle-publish.yml
