name: create a release and a tag if
on:
  push:
    branches:
#      - master
      - test-more-4

jobs:
  simple:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'Setup the release ')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Set env // from https://stackoverflow.com/a/57969570
#        run: echo "VERSION=$(echo ${{github.event.head_commit.message}} | awk '{print $NF}')" >> $GITHUB_ENV
        run: echo "VERSION=$(awk -F'=' '/LIBRARY_VERSION/ {printf "%s", $NF; exit}' gradle.properties)" >> $GITHUB_ENV
      - name: Print version
        run: echo "Version is $VERSION"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token

        with:
          tag_name: v${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          body_path: RELEASE.md
          draft: false
          prerelease: false
