name: create a release and a tag it
on:
  push:
    branches:
      - master
      - test12

jobs:
  simple:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'Setup the release')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Set env // from https://stackoverflow.com/a/57969570
        run: |
          echo "VERSION=$(awk -F'=' '/LIBRARY_VERSION/ {printf "%s", $NF; exit}' gradle.properties)" >> $GITHUB_ENV
          CHANGES=$(awk 'BEGIN {a = 0} /###/ { if (a == 0) { a = 1 } else { exit 0 } }a' CHANGELOG.md)
          echo "CHANGES<<EOF" >> $GITHUB_ENV
          echo "$CHANGES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Print version
        run: echo "Version is $VERSION"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token

        with:
          tag_name: v${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          body: ${{ env.CHANGES }}
          draft: false
          prerelease: false
