name: create a release and a tag if
on:
  push:
    branches:
      - master

jobs:
  simple:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'Setup the release ')
    steps:
      - name: step1
        run: |
          VERSION=$(echo ${{github.event.head_commit.message}} | awk '{print $NF}')
          echo $VERSION
